package com.example.Java.backend.dto;

import java.util.List;

import com.example.Java.backend.entities.Excursion;

import lombok.Data;

public class ExcursionResponseDTO {

        private Embedded _embedded;
    // Other fields...

    @Data
    public class Embedded {
        private List<Excursion> excursions;

        // Constructors, getters, setters will be automatically generated by Lombok
    }

    public void setExcursions(List<Excursion> excursions) {
        if (_embedded == null) {
            _embedded = new Embedded();
        }
        _embedded.setExcursions(excursions);
    }
    
}
