package com.example.Java.backend.dto;



import java.util.List;

import com.example.Java.backend.entities.Vacation;

import lombok.Data;

@Data
public class VacationResponseDTO {
    

    private Embedded _embedded;
    // Other fields...

    @Data
    public class Embedded {
        private List<Vacation> vacations;

        // Constructors, getters, setters will be automatically generated by Lombok
    }

    public void setVacations(List<Vacation> vacations) {
        if (_embedded == null) {
            _embedded = new Embedded();
        }
        _embedded.setVacations(vacations);
    }
}
